[http]
enabled = true
bind_to_address = 0.0.0.0
port = 1780
doc_root = /usr/share/snapserver/snapweb

[tcp]
enabled = true
bind_to_address = 0.0.0.0
port = 1705

[stream]
bind_to_address = 0.0.0.0
port = 1704
source = librespot:///usr/local/bin/librespot?name=spotify&devicename=SyrenSystem&bitrate=320&volume=100&disable_audio_cache=true&codec=pcm&params=--ap-port%20443%20--zeroconf-interface%20__ZEROCONF_INTERFACE__
source = tcp://0.0.0.0:4953?name=laptop&mode=server&sampleformat=48000:16:2&chunk_ms=10&idle_threshold=100&codec=pcm
buffer = 200

[streaming_client]
initial_volume = 0

[logging]
sink = stdout
filter = *:info
