[http]
enabled = true
bind_to_address = 0.0.0.0
port = 1780
doc_root = /usr/share/snapserver/snapweb

[tcp]
enabled = true
bind_to_address = 0.0.0.0
port = 1705

[stream]
bind_to_address = 0.0.0.0
port = 1704
source = librespot:///usr/local/bin/librespot?name=default&devicename=SyrenSystem&bitrate=320&volume=100&disable_audio_cache=true&codec=flac&params=--ap-port%20443
buffer = 1000

[streaming_client]
initial_volume = 100

[logging]
sink = stdout
filter = *:info
